### ISSUE TITLE
Alt and Title not taken from the image metadata

### ISSUE THREAD

**Issue by rdk-pmis** [netresearch/t3x-rte_ckeditor_image#14]
When not adding title and alt in the image dialogue, the frontend doesn't show the title and alt attribute values, while they are configured in the Typo3 filelist (and even shown in the dialogue)
![image](https://user-images.githubusercontent.com/17740943/29456529-5fa7c5be-8416-11e7-937c-ad1fc79fbaea.png)
Leads to 
![image](https://user-images.githubusercontent.com/17740943/29456548-7500b826-8416-11e7-9ca3-f7559df45631.png)

**Comment by copitz** [comment]
I'm sorry - I can't reproduce this.

**Comment by mkrappitz** [comment]
Can reproduce on EXT:rte_ckeditor_image 8.7.4 and TYPO3 8.7.19. Am currently investigating this in the source of EXT:rte_ckeditor_image - resp. in the ImageRenderingController, but am very surprised / confused that not even a die() call at the beginning of }Netresearch\RteCKEditorImage\Controller\ImageRenderingController->renderImageAttributes has any effect in the uncached frontend rendering of rte images. Is this method not responsible for the frontend rendering of the rte images, as the name would suggest? Any hints?

**Comment by muh-nr** [comment]
Is this still an issue?
I can't reproduce.

**Comment by mkrappitz** [comment]
Is there a fix been done in the meantime?

**Comment by muh-nr** [comment]
@mkrappitz 

No, there was no fix.
For me the die(); works as well as the alt/title rendering.
Do you still have the problem?

**Comment by mkrappitz** [comment]
Well, I didn't check this lately, but I also didn't change anyhting here, So I suppose yes.

**Comment by muh-nr** [comment]
@mkrappitz 

Especially for linked images, currently the title/alt fallback doesn't work.
This is going to be fixed in branch [dev-linked-images](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-linked-images).
Please have a try.
Maybe this solves your problem.

**Comment by mkrappitz** [comment]
Is going to be fixed or has been fixed in this branch?

**Comment by muh-nr** [comment]
Is fixed by the branch ;)

**Comment by mkrappitz** [comment]
Is this part of the TER release 8.7.5 of the extension? Then the bug is not fixed for us. We just updated and see no change in this aspect.

**Comment by muh-nr** [comment]
No. Please check the master.

**Comment by mkrappitz** [comment]
ok, just did that. master indeed fixes this problem, but breaks new stuff. The frontend rendering changes in our case from former:
```html
<p>
    <a href="some-link" title="Open external link in new window" target="_blank" class="button">
        <img src="some-image.svg" style="" alt="" width="20" height="20">
        Contact us
    </a>
    ...
</p>
```

to now:
```html
<p>
    <a href="some-link" title="Open external link in new window" target="_blank" class="button">
        <img src="some-image.svg" alt="logo newsletter" title="" width="20" height="20">
    </a>
</p>
```

So the text "Contact us" directly after the image in the rte gets removed in frontend rendering, even though it is still present in the rte.

**Comment by muh-nr** [comment]
Yes, simulating the default link rendering within an own parser is very difficult.
Could you just try to link the images and the text separately?

**Comment by mkrappitz** [comment]
I could, but this example is take from a huge content site, with over 60.000 of elements. Too much to check and change them all, so changing the content is not a feasible option here, unfortunately.

**Comment by muh-nr** [comment]
We are working on this...

**Comment by muh-nr** [comment]
Please have a look at #42

**Comment by muh-nr** [comment]
Should be working now.

**Comment by mkrappitz** [comment]
It does!
